apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/gitlab
    server: 10.124.148.143